api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core-aspnet"
  name = "ASPNetCore Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "7615661cd3814a4698b32d12d7a3d31b5739e011492a7920f5eb31ce5f741dd9"
    source = "https://download.visualstudio.microsoft.com/download/pr/3a4fa17f-1c69-497c-b04d-b2d323b58f17/0994ea07591e8592f95f6057f5a68bdc/aspnetcore-runtime-2.1.15-linux-x64.tar.gz"
    source_sha256 = "9a7f6a54a9923d0e5a3f12b4e25f67e4e6e4f2085787eeeb3724d4ffcec41907"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.15.linux-amd64-any-stack-7615661c.tar.xz"
    version = "2.1.15"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "f18141e2ee4a43c0c56c88a10a91a48b4f3716590860410b2cdc9b288633b314"
    source = "https://download.visualstudio.microsoft.com/download/pr/5fa590c6-dbb4-41d2-81a1-d6650d3b390c/6f7c69995ebadeaa43fcd8872083cd58/aspnetcore-runtime-2.1.16-linux-x64.tar.gz"
    source_sha256 = "02e94df0a0b071ba58ab3a30cfe5fe7dd4a82d2fb4f8d1ca027dc7f0af224bc6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.16.linux-amd64-any-stack-f18141e2.tar.xz"
    version = "2.1.16"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "ed516e21098ee284ea0c4eb5d5e62904ff651789be442e77627df004bda55ecd"
    source = "https://download.visualstudio.microsoft.com/download/pr/deeee432-fd3c-4dbc-bc06-cbf166cbcfb7/04747ae7a0ea63e01b6f932cccdcf837/aspnetcore-runtime-3.1.1-linux-x64.tar.gz"
    source_sha256 = "10079255bc31a7a6b57845f22ccae585e2275a48108e43103cd6c700d38f5435"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.3.1.1.linux-amd64-any-stack-ed516e21.tar.xz"
    version = "3.1.1"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "5736292f80a9d921989072162b7ac6aca4f6381957c9e15c30e1b9fa073eb14e"
    source = "https://download.visualstudio.microsoft.com/download/pr/2d72ee67-ac4d-42c6-97d9-a26a28201fc8/977ad14b99b6ed03dcefd6655789e43a/aspnetcore-runtime-3.1.2-linux-x64.tar.gz"
    source_sha256 = "d3ec949528d698d9cd7016b9276b4c01a949c4970d168295b6506d7399d608f1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.3.1.2.linux-amd64-any-stack-5736292f.tar.xz"
    version = "3.1.2"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
