api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core-aspnet"
name = "ASPNetCore Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "2c11fc1cda49ec650372174f551955a26bdf56c2a5d6596f5961c0db801d9e9c"
source = "https://download.microsoft.com/download/A/7/8/A78F1D25-8D5C-4411-B544-C7D527296D5E/aspnetcore-runtime-2.1.4-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "517195f38f7553fffec01a2bd3d09ed4ad589823094426a3febb70c7e77319d3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.4.linux-amd64-cflinuxfs3-2c11fc1c.tar.xz"
version = "2.1.4"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "73e94151eed976ec82a02158bee1e45cd48b86be09657f7b9d45ef738793ded8"
source = "https://download.visualstudio.microsoft.com/download/pr/97fce50e-e736-41c3-a700-d83d43178197/4c00b063affdbc940dd16f62c68d1505/aspnetcore-runtime-2.1.5-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "775bcb800f186461b54f2ca0dc858c2a34dc82f95ad060681e8f440c48c2b291"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.5.linux-amd64-cflinuxfs3-73e94151.tar.xz"
version = "2.1.5"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "68f5a6ade61e058db93e8ad3fc763c43aa3e83a307e6650008544331e1a8bcf8"
source = "https://download.visualstudio.microsoft.com/download/pr/5ecfed21-c776-4924-b734-126400fd324a/4e1bfb9c870ffcf99b1bf953b91ef072/aspnetcore-runtime-2.1.6-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "3d4a4135627c07716447fd058b91c8c45de6b5c385f1245cae8a7a62dec93ce9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.6.linux-amd64-cflinuxfs3-68f5a6ad.tar.xz"
version = "2.1.6"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "e0b38608878bde5d1791468178ba765ddb7447098b0acd45c7f7db1f94168bb8"
source = "https://download.visualstudio.microsoft.com/download/pr/085b427b-66f6-4cf5-bee3-5f4cbef2b72c/9c1ad276cf957258d123a3b268ec9304/aspnetcore-runtime-2.1.7-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "e2522c4a4ec94245914b7b93b30d0f92b6ddb6c1e08458b4425bc97a313b9c27"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.7.linux-amd64-cflinuxfs3-e0b38608.tar.xz"
version = "2.1.7"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "dbf8b6f41779deb5fbb49262c849ecddfd8bde5c541585d7ec807544aaf0fa07"
source = "https://download.visualstudio.microsoft.com/download/pr/927cbf41-157f-488b-ac7d-32034defebc3/41b011418f795d5a76bf930ad57a055b/aspnetcore-runtime-2.1.8-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "88831762a54fec8f8d1408a31a1a6dd226ffaf72eac6373ac93ccac21ec4fa56"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.8.linux-amd64-cflinuxfs3-dbf8b6f4.tar.xz"
version = "2.1.8"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "4b5bb74b3bc311b191c82381e958511c41f4e5a3b0e27ddbe8d8f15d2e977bf7"
source = "https://download.visualstudio.microsoft.com/download/pr/c5075a91-1ae1-45f8-98ac-412b01697336/7c08df006985d6e631e5cf4de6811085/aspnetcore-runtime-2.1.9-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "b0f26f38c156ff4be425817ba042e37ecdefcf020585a1acd0c2d6139f34a9a8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.9.linux-amd64-cflinuxfs3-4b5bb74b.tar.xz"
version = "2.1.9"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "25139da997ed34a6a6cea788a6941a9a0398bae373bcea85dc2452abd88ed84c"
source = "https://download.visualstudio.microsoft.com/download/pr/5967af9f-21d4-4b2f-a166-52af457d02aa/713e9a0f3753cf79171594bbdb92ad89/aspnetcore-runtime-2.1.10-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "73abc450bf9838a56866f23806e7ec76243f8a659f9fe61e8f4e3baf1f80ff7c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.10.linux-amd64-cflinuxfs3-25139da9.tar.xz"
version = "2.1.10"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "3a241ca73f2046c07b4c8aba6f10ce76c6fc534f94a97e5bf4fff0ea0a9bc732"
source = "https://download.visualstudio.microsoft.com/download/pr/5f0a5410-f311-47d6-a0d7-f8afe245bfc2/d4b0370ee8fdac3e8d8b0da7ec6b649a/aspnetcore-runtime-2.1.11-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "fab14e2ad118f3ab3076b482ae3fbab845fa4b12321f3e3c0e5a1d382c854cb8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.11.linux-amd64-cflinuxfs3-3a241ca7.tar.xz"
version = "2.1.11"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "2072ed7b9ea76b7b774f43fc09a29bee408b05516a06ec7efd431e1a20fb2153"
source = "https://github.com/dotnet/cli/archive/243f6de49b3c4c16dd1a6413c39f463fcbdcf58d.tar.gz"
source_sha256 = "47e87c339c0069b6f487fa7077d7db41eff18d9334b1753d885d6568062b45cc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.12.linux-amd64-cflinuxfs3-2072ed7b.tar.xz"
version = "2.1.12"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "0cd6f1e17e44ee552de3b8601aaf75535190cfd30dae4edcdd3fb73589a2abc0"
source = "https://github.com/dotnet/cli/archive/9b0b46aacc95a4e12fa7df23aa2c19dec1dacc03.tar.gz"
source_sha256 = "ecedcefdf5d8090e83c4f150ea2fa802f5dd92a2c3e1bb23b82a69fe1a9c9f18"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.13.linux-amd64-cflinuxfs3-0cd6f1e1.tar.xz"
version = "2.1.13"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "36e2c8c258146d0cfc33152b5885f99623168ad76918ad640da7e003280e0dbc"
source = "https://download.visualstudio.microsoft.com/download/pr/69ee3993-54fe-4687-9388-25b1e0c888fb/df2ba0637e68f6e8ee212a38756a4002/aspnetcore-runtime-2.2.0-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "30af25564a9b71a2033b8ce7f78de2232beca4263dc0d6fbaed1e39610e806aa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.0.linux-amd64-cflinuxfs3-36e2c8c2.tar.xz"
version = "2.2.0"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "0f1ae8609c3af78e3c4640a91bd5c2c0ff72f1ff6b3202ffa1252c84b43fece6"
source = "https://download.visualstudio.microsoft.com/download/pr/53cace8f-2907-487e-84d7-bc7a7ba5de05/326704ffa2ef9d4dcd0db2f1da996ebb/aspnetcore-runtime-2.2.1-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "8a275315b36f6f66038049c34dcb4808e0fa4ece49651957f7be83d6b235f4b8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.1.linux-amd64-cflinuxfs3-0f1ae860.tar.xz"
version = "2.2.1"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "18af55ea240edb082072da8f353e6e9e99843a7d871167b314526bce02bb9611"
source = "https://download.visualstudio.microsoft.com/download/pr/168bba07-32dc-4612-ab01-7632d412c4cd/e1ecbf16d84e504c1d66d7a7573c9171/aspnetcore-runtime-2.2.2-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "c3249eb70b2f74f7ce6481ae1928553034f7b18b04f7b8ed96d60cb9528afdcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.2.linux-amd64-cflinuxfs3-18af55ea.tar.xz"
version = "2.2.2"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "023e33ef1fe0517e8e5cf66192510b4ee08fdad2f012e5fc05de374e61a09a3d"
source = "https://download.visualstudio.microsoft.com/download/pr/dabca6d9-19e5-44b6-a402-a627fae42d26/e36d703f5d281ec8662422bfa62c2fdd/aspnetcore-runtime-2.2.3-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "9d71c8312ec3448ae957cfbf4d4777c1924e34cb287d0f0d0f4853ce4ffc5355"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.3.linux-amd64-cflinuxfs3-023e33ef.tar.xz"
version = "2.2.3"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "9c47a71ea47cb16345e28f6437644b0cb24806339a3bfa7776c01f3391e07332"
source = "https://download.visualstudio.microsoft.com/download/pr/61a33dc2-fc56-4bbe-b564-d232172eb210/d8006a719a3bcc65d2937a909623afcb/aspnetcore-runtime-2.2.4-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "7c4d8eb399e21d656cc19dd7b99aea6b8267419d2284d872606ec984d7af9293"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.4.linux-amd64-cflinuxfs3-9c47a71e.tar.xz"
version = "2.2.4"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "faa8a01f9ab4bbcc4bed7a2c843cefcc94aec2234b7310cceb1e3bd02b6b7494"
source = "https://download.visualstudio.microsoft.com/download/pr/411768dc-83c3-4b15-acd3-d4490aad6dde/90e0b4848a18585ab4fc170c8d7a2fbe/aspnetcore-runtime-2.2.5-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "5e5ecdb6e20624aa7b83ff6551706e12ba287a71f143a65c1b2959c19750e37b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.5.linux-amd64-cflinuxfs3-faa8a01f.tar.xz"
version = "2.2.5"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "451bc596fb932aa34f0f7a508278c67b65691a1379a5fe47a213caed59757ca9"
source = "https://github.com/dotnet/cli/archive/3e0e612cb176daae0fce6ca54608d40428c9d27e.tar.gz"
source_sha256 = "e7a0d34b933d2dcac5d7536ab850f75af967b52567c82cd75e36e7d8145c9c2e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.6.linux-amd64-cflinuxfs3-451bc596.tar.xz"
version = "2.2.6"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "ba5b24cf59ed4dbb89c7c96587ce498e9cf53c9ee417aee92f75958f1e8a30bf"
source = "https://github.com/dotnet/cli/archive/7a42b83262bb2b52804a2c14b4fad289d794c8be.tar.gz"
source_sha256 = "0b4a86f13d63418636762a997ecac5acd5ce5a8d59ff28f8a0f3e7a0c701ff4e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.7.linux-amd64-cflinuxfs3-ba5b24cf.tar.xz"
version = "2.2.7"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
