api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core-aspnet"
  name = "ASPNetCore Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "2072ed7b9ea76b7b774f43fc09a29bee408b05516a06ec7efd431e1a20fb2153"
    source = "https://github.com/dotnet/cli/archive/243f6de49b3c4c16dd1a6413c39f463fcbdcf58d.tar.gz"
    source_sha256 = "47e87c339c0069b6f487fa7077d7db41eff18d9334b1753d885d6568062b45cc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.12.linux-amd64-cflinuxfs3-2072ed7b.tar.xz"
    version = "2.1.12"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "0cd6f1e17e44ee552de3b8601aaf75535190cfd30dae4edcdd3fb73589a2abc0"
    source = "https://github.com/dotnet/cli/archive/9b0b46aacc95a4e12fa7df23aa2c19dec1dacc03.tar.gz"
    source_sha256 = "ecedcefdf5d8090e83c4f150ea2fa802f5dd92a2c3e1bb23b82a69fe1a9c9f18"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.13.linux-amd64-cflinuxfs3-0cd6f1e1.tar.xz"
    version = "2.1.13"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "ad55d0ff01c0be03aeb14c428cebf749e7dfedc401e16ef793ec7756752ba70b"
    source = "https://download.visualstudio.microsoft.com/download/pr/22e9f27e-12cd-4ba9-86ce-113cbe7c55c2/a1097e49b4da2c1949919e752264f691/aspnetcore-runtime-2.1.14-linux-x64.tar.gz"
    source_sha256 = "e8f1895914c8a7cb619d16600887fe25aab0ec616cd22fef668c0d0b7558d56a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.1.14.linux-amd64-any-stack-ad55d0ff.tar.xz"
    version = "2.1.14"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "451bc596fb932aa34f0f7a508278c67b65691a1379a5fe47a213caed59757ca9"
    source = "https://github.com/dotnet/cli/archive/3e0e612cb176daae0fce6ca54608d40428c9d27e.tar.gz"
    source_sha256 = "e7a0d34b933d2dcac5d7536ab850f75af967b52567c82cd75e36e7d8145c9c2e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.6.linux-amd64-cflinuxfs3-451bc596.tar.xz"
    version = "2.2.6"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "ba5b24cf59ed4dbb89c7c96587ce498e9cf53c9ee417aee92f75958f1e8a30bf"
    source = "https://github.com/dotnet/cli/archive/7a42b83262bb2b52804a2c14b4fad289d794c8be.tar.gz"
    source_sha256 = "0b4a86f13d63418636762a997ecac5acd5ce5a8d59ff28f8a0f3e7a0c701ff4e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.7.linux-amd64-cflinuxfs3-ba5b24cf.tar.xz"
    version = "2.2.7"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "632a1a7437cbbfacb87a17f95349d0075e1547852df0e363ee2b56e0a3104cee"
    source = "https://download.visualstudio.microsoft.com/download/pr/e716faa4-345c-45a7-bd1f-860cdf422b75/fa8e57167f3bd4bf20b8b60992cf184f/aspnetcore-runtime-2.2.8-linux-x64.tar.gz"
    source_sha256 = "e0f5383b89afcde037510bdd06c2f584d6593e28b9824f322b55a1b04bd0ccf2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.8.linux-amd64-any-stack-632a1a74.tar.xz"
    version = "2.2.8"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "bc189754a9f465d9014d137058990f4b44496ebb1fa9885518043b4ae6566f8a"
    source = "https://download.visualstudio.microsoft.com/download/pr/b0c44e05-b7a1-4221-94ec-a0c0d3a11eed/afc61567dd6db8f097e244871889458c/aspnetcore-runtime-3.0.0-linux-x64.tar.gz"
    source_sha256 = "8d28aa53f47e8b2ef5c39ddee75cc22527ace332c528bbe85da99bf1b4906b36"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.3.0.0.linux-amd64-cflinuxfs3-bc189754.tar.xz"
    version = "3.0.0"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "220c2866ed7adc00ce08ffcf529072291d782863783fd4e9e79d7522211dd8d6"
    source = "https://download.visualstudio.microsoft.com/download/pr/67362f50-42cc-42d0-919f-c868e8a70db8/3ecdc7b53899df7e2e260b6b7b3f25c1/aspnetcore-runtime-3.0.1-linux-x64.tar.gz"
    source_sha256 = "21e578933c272f4834b9080002ba8551108cf9257a557594b49e727d972df565"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.3.0.1.linux-amd64-any-stack-220c2866.tar.xz"
    version = "3.0.1"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "0bc23646969edc191ede9cf60f074cd9afc3cbbf59b72016dee1201fd8928d8a"
    source = "https://download.visualstudio.microsoft.com/download/pr/30915c37-fa5a-4930-b4e6-b4130e4596b2/38d531c10dc56950f17f3c604e9a2ebc/aspnetcore-runtime-3.1.0-linux-x64.tar.gz"
    source_sha256 = "152ff377482d234b06ed2db85fe437e1975008c5fe6722bc8a300bad6a4ac578"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.3.1.0.linux-amd64-cflinuxfs3-0bc23646.tar.xz"
    version = "3.1.0"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
