api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core-aspnet"
name = "ASPNetCore Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "dotnet-aspnet"
sha256 = "9c578eee5e7026bd74c101b0d0950650ad166b9899aa69f975e943c3ca25f955"
source = "https://github.com/dotnet/cli/archive/729b316c13bf9289b033272c07c7dfd046ffbcaf.tar.gz"
source_sha256 = "1e2463cc161ae8f516aa047b09bef29aff6732f8346626b312b3acd75e9191ba"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore.2.2.6.linux-amd64-cflinuxfs3-9c578eee.tar.xz"
version = "2.2.6"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
